#!/bin/bash

case "$1" in
#!/bin/bash

case "$1" in
    remove)
        rm -rf /var/lib/dnstapir/edm
        ;;
    purge)
        rm -rf /var/lib/dnstapir/edm
        rm -rf /etc/dnstapir/edm
        ;;
esac
    remove)
        rm -rf /var/lib/dnstapir/edm
        ;;
    purge)
        rm -rf /var/lib/dnstapir/edm
        rm -rf /etc/dnstapir/edm
        ;;
esac
