#!/bin/bash

case "$1" in
    rm /usr/bin/dnstapir-edm
    remove)
        rm -rf /var/lib/dnstapir/edm
        ;;
    purge)
        rm -rf /var/lib/dnstapir/edm
        rm -rf /etc/dnstapir/edm
        ;;
esac
